---
- name: Print Linux role message
  debug:
    msg: "Linux role is working successfully"

- name: Create test file on Linux
  copy:
    content: "This file was created by Ansible from AWX."
    dest: /tmp/ansible_linux_test.txt

- name: Show final success message
  debug:
    msg: "Linux playbook completed successfully from AWX"