[linux_servers]
localhost ansible_connection=local

[windows_servers]
win1 ansible_host=192.168.134.1 ansible_user=ansibleadmin ansible_password=Ansible@123

[windows_servers:vars]
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore